name: e_chalan
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_bottom_navigation_bar: ^0.3.2 
  cached_network_image: ^3.1.0+1
  cloud_firestore: ^3.1.0
  enough_mail: ^1.3.6
  fading_edge_scrollview: ^2.0.1
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_localizations:
    sdk: flutter 
  flutter_mobile_vision_2: ^0.1.13
  flutter_svg: ^0.23.0+1
  hive: ^2.0.4
  intl: ^0.17.0
  logger: ^1.1.0
  lottie: ^1.2.1
  mailer: ^5.0.2
  multi_select_flutter: ^4.0.0
  package_info_plus: ^1.3.0
  paginate_firestore: ^1.0.3
  path_provider: ^2.0.7
  provider: ^6.0.1 
  shared_preferences: ^2.0.9
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
